/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.codeWithSrb.Kafka.schema;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
/** Video statistics key */
@org.apache.avro.specific.AvroGenerated
public class VideoStatisticsKey extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4521927345456436776L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"VideoStatisticsKey\",\"namespace\":\"com.codeWithSrb.Kafka.schema\",\"doc\":\"Video statistics key\",\"fields\":[{\"name\":\"VideoStatisticsId\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<VideoStatisticsKey> ENCODER =
      new BinaryMessageEncoder<VideoStatisticsKey>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<VideoStatisticsKey> DECODER =
      new BinaryMessageDecoder<VideoStatisticsKey>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<VideoStatisticsKey> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<VideoStatisticsKey> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<VideoStatisticsKey>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this VideoStatisticsKey to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a VideoStatisticsKey from a ByteBuffer. */
  public static VideoStatisticsKey fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence VideoStatisticsId;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public VideoStatisticsKey() {}

  /**
   * All-args constructor.
   * @param VideoStatisticsId The new value for VideoStatisticsId
   */
  public VideoStatisticsKey(java.lang.CharSequence VideoStatisticsId) {
    this.VideoStatisticsId = VideoStatisticsId;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return VideoStatisticsId;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: VideoStatisticsId = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'VideoStatisticsId' field.
   * @return The value of the 'VideoStatisticsId' field.
   */
  public java.lang.CharSequence getVideoStatisticsId() {
    return VideoStatisticsId;
  }

  /**
   * Sets the value of the 'VideoStatisticsId' field.
   * @param value the value to set.
   */
  public void setVideoStatisticsId(java.lang.CharSequence value) {
    this.VideoStatisticsId = value;
  }

  /**
   * Creates a new VideoStatisticsKey RecordBuilder.
   * @return A new VideoStatisticsKey RecordBuilder
   */
  public static com.codeWithSrb.Kafka.schema.VideoStatisticsKey.Builder newBuilder() {
    return new com.codeWithSrb.Kafka.schema.VideoStatisticsKey.Builder();
  }

  /**
   * Creates a new VideoStatisticsKey RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new VideoStatisticsKey RecordBuilder
   */
  public static com.codeWithSrb.Kafka.schema.VideoStatisticsKey.Builder newBuilder(com.codeWithSrb.Kafka.schema.VideoStatisticsKey.Builder other) {
    return new com.codeWithSrb.Kafka.schema.VideoStatisticsKey.Builder(other);
  }

  /**
   * Creates a new VideoStatisticsKey RecordBuilder by copying an existing VideoStatisticsKey instance.
   * @param other The existing instance to copy.
   * @return A new VideoStatisticsKey RecordBuilder
   */
  public static com.codeWithSrb.Kafka.schema.VideoStatisticsKey.Builder newBuilder(com.codeWithSrb.Kafka.schema.VideoStatisticsKey other) {
    return new com.codeWithSrb.Kafka.schema.VideoStatisticsKey.Builder(other);
  }

  /**
   * RecordBuilder for VideoStatisticsKey instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<VideoStatisticsKey>
    implements org.apache.avro.data.RecordBuilder<VideoStatisticsKey> {

    private java.lang.CharSequence VideoStatisticsId;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.codeWithSrb.Kafka.schema.VideoStatisticsKey.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.VideoStatisticsId)) {
        this.VideoStatisticsId = data().deepCopy(fields()[0].schema(), other.VideoStatisticsId);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing VideoStatisticsKey instance
     * @param other The existing instance to copy.
     */
    private Builder(com.codeWithSrb.Kafka.schema.VideoStatisticsKey other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.VideoStatisticsId)) {
        this.VideoStatisticsId = data().deepCopy(fields()[0].schema(), other.VideoStatisticsId);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'VideoStatisticsId' field.
      * @return The value.
      */
    public java.lang.CharSequence getVideoStatisticsId() {
      return VideoStatisticsId;
    }

    /**
      * Sets the value of the 'VideoStatisticsId' field.
      * @param value The value of 'VideoStatisticsId'.
      * @return This builder.
      */
    public com.codeWithSrb.Kafka.schema.VideoStatisticsKey.Builder setVideoStatisticsId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.VideoStatisticsId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'VideoStatisticsId' field has been set.
      * @return True if the 'VideoStatisticsId' field has been set, false otherwise.
      */
    public boolean hasVideoStatisticsId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'VideoStatisticsId' field.
      * @return This builder.
      */
    public com.codeWithSrb.Kafka.schema.VideoStatisticsKey.Builder clearVideoStatisticsId() {
      VideoStatisticsId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public VideoStatisticsKey build() {
      try {
        VideoStatisticsKey record = new VideoStatisticsKey();
        record.VideoStatisticsId = fieldSetFlags()[0] ? this.VideoStatisticsId : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<VideoStatisticsKey>
    WRITER$ = (org.apache.avro.io.DatumWriter<VideoStatisticsKey>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<VideoStatisticsKey>
    READER$ = (org.apache.avro.io.DatumReader<VideoStatisticsKey>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
